[package]
name = "csr-with-tailwind"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
leptos = { version = "0.6", features = ["csr", "nightly"] }
leptos_primitives = { path = "../../" }
